create table public.project_files (
    id bigint generated by default as identity primary key,

    project_id bigint not null,

    name text not null,

    storage_path text not null,

    mime_type text,

    size bigint,

    created_at timestamptz not null default now(),

    created_by bigint,

    constraint project_files_project_id_fkey
        foreign key (project_id)
        references public.projects(id)
        on delete cascade,

    constraint project_files_created_by_fkey
        foreign key (created_by)
        references public.users(id)
        on delete set null
);

create index project_files_project_id_idx
    on public.project_files(project_id);

create unique index project_files_storage_path_idx
    on public.project_files(storage_path);